import Footer from "../components/client/Footer";
import Header from "../components/client/Header";
import "./../globals.scss";
import "swiper/css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function  RootLayout({ children}) {

	return (
		<html lang="en">
			<body cz-shortcut-listen="false">
				<Header/>
				{children}
				<Footer />
			</body>
		</html>
	);
}
