import "./globals.scss";
import "swiper/css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function  RootLayout({ children}) {

	return (
		<html lang="en">
			<body cz-shortcut-listen="false">
				{children}
			</body>
		</html>
	);
}